#!/usr/bin/env bash
#  write a Bash script with the minimum number of commands to automate your fix.

# Changes port in Nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
