#!/usr/bin/env bash
#  write a Bash script with the minimum number of commands to automate your fix.
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
