#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

new="80 default_server"
old="200 default_server"
sudo sed -i "s/200/80/" /etc/nginx/sites-enabled/default

sudo service nginx restart
